from django.db import models

# Create your models here.
class Deliveries(models.Model):
    match_id = models.IntegerField()
    inning = models.IntegerField()
    batting_team = models.CharField(max_length=200)
    bowling_team = models.CharField(max_length=200)
    over = models.IntegerField()
    ball = models.IntegerField()
    batsman = models.CharField(max_length=200)
    non_striker = models.CharField(max_length=200)
    bowler = models.CharField(max_length=200)
    is_super_over = models.BooleanField(default=False)
    wide_runs = models.IntegerField()
    bye_runs = models.IntegerField()
    legbye_runs = models.IntegerField()
    noball_runs = models.IntegerField()
    penalty_runs = models.IntegerField()
    batsman_runs = models.IntegerField()
    extra_runs = models.IntegerField()
    total_runs = models.IntegerField()
    player_dismissed = models.CharField(max_length=200,null=True,blank=True,default=None)
    dismissal_kind = models.CharField(max_length=200,null=True,blank=True,default=None)
    fielder = models.CharField(max_length=200,null=True,blank=True,default=None)


class Matches(models.Model):
    season = models.IntegerField()
    city = models.CharField(max_length=100)
    match_date = models.DateField()
    team1 = models.CharField(max_length=200)
    team2 = models.CharField(max_length=200)
    toss_winner = models.CharField(max_length=200)
    toss_decision = models.CharField(max_length=200)
    result = models.CharField(max_length=50)
    dl_applied = models.BooleanField(default=False)
    winner = models.CharField(max_length=200)
    win_by_runs = models.IntegerField()
    win_by_wickets = models.IntegerField()
    player_of_match = models.CharField(max_length=100)
    venue = models.CharField(max_length=255)
    umpire1 = models.CharField(max_length=100,null=True,blank=True,default=None)
    umpire2 = models.CharField(max_length=100,null=True,blank=True,default=None)
    umpire3 = models.CharField(max_length=100,null=True,blank=True,default=None)
